# Generated by Django 4.2 on 2023-04-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="Add A Content",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("image", models.ImageField(upload_to="photos/%y/%m/%d")),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("phone", "phone"), ("tab", "tab")],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mulham Product",
                "ordering": ["name"],
            },
        ),
    ]
