# Generated by Django 4.2 on 2023-04-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"], "verbose_name": "Product"},
        ),
    ]
